### ISSUE TITLE
Redundant Code

### ISSUE THREAD

**Issue by coderkabh** [dbc2201/LinkedListADTTemplate#1]
On line 131 you copied data of head into a variable temp then on line 134 you checked head should not be equal to null that's correct but on line 142 you checked that temp is not equal to null.
My question is if you have copied data of head into temp then both will have same content then checking once on line 134 is enough.
Correct me if I'm wrong. I'm still learning.

**Comment by dbc2201** [comment]
Yes! you are absolutely correct @coderkabh . It was just a breakdown of the steps to make it a little more understandable.
